# Generated by Django 6.0.2 on 2026-04-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_course_description_alter_course_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'sent_at'], name='main_sugges_ip_addr_7df383_idx')],
            },
        ),
    ]
