# Generated by Django 6.0.2 on 2026-04-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_suggestionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('cloud', 'Computação em Nuvem'), ('networks', 'Redes'), ('programming', 'Programação'), ('cybersecurity', 'Cybersecurity'), ('languages', 'Idiomas'), ('softskills', 'Soft Skills')], default='programming', max_length=20),
        ),
    ]
